"""user_travel_history table

Revision ID: 22c6b74494d4
Revises: 9ae6c229e0fd
Create Date: 2020-02-25 02:06:46.652420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c6b74494d4'
down_revision = '9ae6c229e0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_travel_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.Column('entry_station', sa.String(length=50), nullable=True),
    sa.Column('exit_station', sa.String(length=50), nullable=True),
    sa.Column('entry_time', sa.String(length=50), nullable=True),
    sa.Column('exit_time', sa.String(length=20), nullable=True),
    sa.Column('fare', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_travel_history')
    # ### end Alembic commands ###
