"""new field named entry time is add

Revision ID: 9ae6c229e0fd
Revises: b9713203cfc6
Create Date: 2020-02-20 02:39:17.094442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae6c229e0fd'
down_revision = 'b9713203cfc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('entry_time', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'entry_time')
    # ### end Alembic commands ###
